import{useNavigate,useParams}from"react-router-dom";import{useStore}from"../data/store";import{brl,dias as diasEntre}from"../lib/calc";import logoDocumento from"../assets/locago-logo-documentos.png";
const WHATSAPP="(62) 98146-9409";
export default function ContratoDocumento(){const{numero}=useParams(),nav=useNavigate(),{getContrato,getCliente}=useStore(),ct=getContrato(numero!);if(!ct)return <main className="page"><div className="empty">Contrato não encontrado.</div></main>;const cli=getCliente(ct.clienteId),dias=diasEntre(ct.inicio,ct.fim),total=ct.total??(ct.locacao+ct.servicos+ct.frete-(ct.desconto||0));return <main className="page contract-page"><div className="budget-toolbar"><button className="btn btn-ghost" onClick={()=>nav(`/app/contratos/${ct.numero}`)}>← Voltar ao contrato</button><button className="btn btn-primary" onClick={()=>window.print()}>Imprimir / Salvar em PDF</button></div><article className="contract-document">
<header className="contract-head"><img src={logoDocumento} alt="LOCAGO — Aluguel de Equipamentos"/><div><span>CONTRATO DE LOCAÇÃO</span><strong>{ct.numero}</strong><small>Emitido em {new Date().toLocaleDateString("pt-BR")}</small></div></header><div className="contract-company"><strong>LOCAGO ALUGUEL DE EQUIPAMENTOS</strong><span>{WHATSAPP}</span></div>
<h1>CONTRATO DE LOCAÇÃO DE EQUIPAMENTOS</h1><section className="contract-parties"><div><small>LOCATÁRIO</small><strong>{cli?.nome||"—"}</strong><span>{cli?.doc||"—"}</span><span>{cli?.tel||"—"} · {cli?.email||"—"}</span><span>{cli?.endereco||"Endereço não informado"}</span></div><div><small>DADOS DA LOCAÇÃO</small><dl><dt>Início</dt><dd>{fmt(ct.inicio)}</dd><dt>Término previsto</dt><dd>{fmt(ct.fim)}</dd><dt>Prazo</dt><dd>{dias} {dias===1?"diária":"diárias"}</dd><dt>Pagamento</dt><dd>{ct.pagamento}</dd></dl></div></section>
<section className="contract-destination"><h2>LOCAL DE UTILIZAÇÃO / ENTREGA</h2><strong>{ct.local}</strong><span>{ct.endereco}</span></section>
<section className="contract-items"><h2>EQUIPAMENTOS LOCADOS</h2><table><thead><tr><th>Descrição</th><th>Qtd.</th><th>Identificação</th><th>Valor</th></tr></thead><tbody>{ct.itens.map((i,n)=><tr key={n}><td><strong>{i.nome}</strong></td><td>{i.qtd||1}</td><td>{i.patrimonio}</td><td><strong>{brl.format(i.valor)}</strong></td></tr>)}</tbody></table><div className="contract-financial"><span>Locação <b>{brl.format(ct.locacao)}</b></span>{ct.servicos>0&&<span>Serviços <b>{brl.format(ct.servicos)}</b></span>}{ct.frete>0&&<span>Frete <b>{brl.format(ct.frete)}</b></span>}{(ct.desconto||0)>0&&<span>Desconto <b>− {brl.format(ct.desconto||0)}</b></span>}<strong>TOTAL DO CONTRATO <b>{brl.format(total)}</b></strong></div></section>
<section className="contract-clauses"><h2>CONDIÇÕES DA LOCAÇÃO</h2><ol><li>O LOCATÁRIO declara receber os equipamentos relacionados em condições de uso e se compromete a utilizá-los exclusivamente para sua finalidade, observando as orientações de segurança.</li><li>O prazo da locação corresponde ao período indicado neste contrato. A prorrogação depende de solicitação e confirmação prévia da LOCAGO.</li><li>O LOCATÁRIO é responsável pela guarda dos equipamentos durante a locação e deve comunicar imediatamente perda, furto, avaria, acidente ou funcionamento irregular.</li><li>Os equipamentos deverão ser devolvidos com os componentes e acessórios recebidos. Danos decorrentes de mau uso serão apurados mediante inspeção e evidências.</li><li>A devolução somente é concluída após o recebimento e a conferência pela LOCAGO. A retirada ou coleta não representa aprovação automática das condições do equipamento.</li><li>Valores adicionais decorrentes de prorrogação, peças ausentes, danos comprovados ou serviços autorizados serão apresentados ao LOCATÁRIO para fechamento.</li></ol></section>
<p className="contract-agreement">As partes declaram ter lido e concordado com as condições acima e com os dados registrados neste documento.</p><section className="contract-signatures"><div><span>________________________________________</span><strong>{cli?.nome||"LOCATÁRIO"}</strong><small>LOCATÁRIO</small></div><div><span>________________________________________</span><strong>LOCAGO ALUGUEL DE EQUIPAMENTOS</strong><small>LOCADORA</small></div></section><footer><strong>LOCAGO · Aluguel de Equipamentos</strong><span>{WHATSAPP} · Contrato gerado pelo sistema LOCAGO</span></footer></article></main>}
function fmt(v:string){return v.split("-").reverse().join("/")}
