import { useEffect,useState } from "react";
import { useNavigate,useSearchParams } from "react-router-dom";
import { useStore } from "../data/store";
import { PageHeader,Tag,useToast } from "../components/ui";
import { atendimentoApi,type ContratoItemOperacionalApi,type DocumentoClienteApi } from "../lib/api";

const TIPO="Comprovante de devolução assinado";
export default function Devolucoes(){
 const {contratos,getCliente,devolverContrato}=useStore();const nav=useNavigate();const {toast}=useToast();const [params]=useSearchParams();
 const [aberto,setAberto]=useState<string|null>(params.get("contrato")),[docs,setDocs]=useState<DocumentoClienteApi[]>([]),[enviando,setEnviando]=useState(false),[confirmando,setConfirmando]=useState(false),[visualizando,setVisualizando]=useState<DocumentoClienteApi|null>(null);
 const [itens,setItens]=useState<ContratoItemOperacionalApi[]>([]),[selecionados,setSelecionados]=useState<string[]>([]);
 const fila=contratos.filter(c=>["Em andamento","Parcialmente expedido","Em inspeção"].includes(c.situacao));
 useEffect(()=>{if(!aberto){setDocs([]);setItens([]);setSelecionados([]);return}Promise.all([atendimentoApi.documentosContrato(aberto),atendimentoApi.itensOperacionaisContrato(aberto)]).then(([d,i])=>{setDocs(d);setItens(i);setSelecionados([])}).catch(()=>{setDocs([]);setItens([]);setSelecionados([])})},[aberto]);
 const via=docs.find(d=>d.tipo===TIPO);
 return <main className="page" style={{maxWidth:1300}}><PageHeader title="Devoluções" sub="Receba o equipamento de forma documentada: gere o comprovante, recolha a assinatura, anexe a via digitalizada e confirme o retorno."/>
 <div className="list-head expedition-grid" style={{marginTop:24}}><span>Contrato</span><span>Cliente e itens</span><span>Origem</span><span>Retorno</span><span>Ação</span></div><div className="list">{fila.map(c=><div className={`expedition-entry${aberto===c.numero?" open":""}`} key={c.numero}><div className="list-row expedition-grid"><button className="mono orange table-link" onClick={()=>nav(`/app/contratos/${c.numero}`)}>{c.numero}</button><span><strong className="block">{getCliente(c.clienteId)?.nome}</strong><small className="muted block">{c.itens.map(i=>i.nome).join(", ")}</small></span><span><span className="block">{c.local}</span><small className="muted block">{c.endereco}</small></span><span className="num" style={{fontSize:18}}>{c.fim.slice(8)}/{c.fim.slice(5,7)}</span><div className="row wrap" style={{gap:6}}><Tag cor="var(--blue)">Aguardando retorno</Tag><button className="btn btn-green btn-sm" onClick={()=>setAberto(a=>a===c.numero?null:c.numero)}>{aberto===c.numero?"Fechar":"Receber devolução"}</button></div></div>
 {aberto===c.numero&&<section className="expedition-step"><div className="expedition-step-head"><div><div className="uplabel">Etapa atual · Devolução</div><h2 className="h2">Comprovante de devolução</h2></div><Tag cor={via?"var(--green)":"var(--yellow)"}>{via?"Via assinada anexada":"Pendente"}</Tag></div><p className="section-note">Confira os equipamentos devolvidos, abra o modelo, recolha a assinatura e anexe a via digitalizada.</p><div className="row wrap" style={{gap:8}}><button className="btn btn-ghost" onClick={()=>nav(`/app/contratos/${c.numero}/devolucao`)}>Visualizar modelo</button><label className={`btn btn-outline${enviando?" disabled":""}`}><input hidden type="file" accept="application/pdf,image/jpeg,image/png" disabled={enviando} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setEnviando(true);try{await atendimentoApi.anexarDocumentoContrato(c.numero,TIPO,f);setDocs(await atendimentoApi.documentosContrato(c.numero));toast("Comprovante de devolução anexado.")}catch(err){toast(err instanceof Error?err.message:"Falha no envio.")}finally{setEnviando(false);e.currentTarget.value=""}}}/>{enviando?"Enviando...":via?"Substituir via assinada":"Anexar via assinada"}</label></div>
 {via&&<div className="client-document-row" style={{marginTop:12}}><button className="client-document-main" onClick={()=>setVisualizando(via)}><span className="document-file-icon">{via.mime==="application/pdf"?"PDF":"IMG"}</span><span><strong>{via.nome}</strong><small>{(via.tamanho/1024/1024).toFixed(2)} MB</small></span></button><div className="client-document-actions"><button className="btn btn-ghost btn-sm" onClick={()=>setVisualizando(via)}>Visualizar</button><a className="btn btn-ghost btn-sm" href={atendimentoApi.urlDownloadDocumentoContrato(via.id)}>Baixar</a></div></div>}
 <div className="operation-selection"><div><strong>Patrimônios devolvidos agora</strong><small>Marque cada unidade física que chegou à loja nesta devolução.</small></div>{itens.flatMap(i=>i.patrimonios.filter(p=>p.estado==="LOCADO").map(p=><label className="operation-option" key={p.codigo}><input type="checkbox" checked={selecionados.includes(p.codigo)} onChange={()=>setSelecionados(s=>s.includes(p.codigo)?s.filter(cod=>cod!==p.codigo):[...s,p.codigo])}/><span><strong>{p.codigo} · {i.descricao}</strong><small>{p.serie||"Série não informada"}</small></span></label>))}</div>
 <div className="expedition-confirm"><span><strong>Confirmar recebimento</strong><small>Somente os patrimônios selecionados seguirão para inspeção.</small></span><button className="btn btn-green" disabled={!via||!selecionados.length||confirmando} onClick={async()=>{setConfirmando(true);try{await devolverContrato(c.numero,selecionados);toast(`${selecionados.length} patrimônio(s) enviado(s) para inspeção.`);setAberto(null);nav(`/app/contratos/${c.numero}`)}catch(err){toast(err instanceof Error?err.message:"Não foi possível receber a devolução.")}finally{setConfirmando(false)}}}>{confirmando?"Confirmando...":"Confirmar devolução selecionada"}</button></div></section>}</div>)}{!fila.length&&<div className="empty">Nenhuma devolução aguardando recebimento.</div>}</div>
 {visualizando&&<div className="document-modal" role="dialog" aria-modal="true" onMouseDown={e=>{if(e.target===e.currentTarget)setVisualizando(null)}}><div className="document-modal-card"><header><span><strong>Comprovante de devolução assinado</strong><small>{visualizando.nome}</small></span><button className="document-modal-close" onClick={()=>setVisualizando(null)}>×</button></header><div className="document-preview">{visualizando.mime.startsWith("image/")?<img src={atendimentoApi.urlDocumentoContrato(visualizando.id)} alt={visualizando.nome}/>:<iframe src={atendimentoApi.urlDocumentoContrato(visualizando.id)} title={visualizando.nome}/>}</div></div></div>}
 </main>
}
