import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { PageHeader, Tag } from "../components/ui";
import { atendimentoApi,type CobrancaApi,type LancamentoFinanceiroApi,type ResumoFinanceiroApi } from "../lib/api";
import { brl } from "../lib/calc";

const zero:ResumoFinanceiroApi={saldo:0,entradas:0,saidas:0,aReceber:0,aPagar:0};
const mesAtual=()=>new Date().toISOString().slice(0,7);

export default function Financeiro(){
  const[resumo,setResumo]=useState(zero),[lista,setLista]=useState<LancamentoFinanceiroApi[]>([]),[cobrancas,setCobrancas]=useState<CobrancaApi[]>([]),[periodo,setPeriodo]=useState(mesAtual()),[visao,setVisao]=useState<"mes"|"dia">("mes"),[dia,setDia]=useState(new Date().toISOString().slice(0,10)),[erro,setErro]=useState("");
  const nav=useNavigate();
  useEffect(()=>{void Promise.all([atendimentoApi.resumoFinanceiro(),atendimentoApi.lancamentosFinanceiros(),atendimentoApi.cobrancas()]).then(([r,l,c])=>{setResumo(r);setLista(l);setCobrancas(c)}).catch(e=>setErro(e instanceof Error?e.message:"Não foi possível carregar o financeiro."))},[]);
  const chavePeriodo=visao==="mes"?periodo:dia;
  const movimentos=useMemo(()=>lista.filter(l=>(l.pagamento||l.vencimento).startsWith(chavePeriodo)),[lista,chavePeriodo]);
  const entradas=movimentos.filter(l=>l.status==="PAGO"&&l.tipo==="ENTRADA").reduce((a,l)=>a+Number(l.valor),0),saidas=movimentos.filter(l=>l.status==="PAGO"&&l.tipo==="SAIDA").reduce((a,l)=>a+Number(l.valor),0);
  const cobrancasPeriodo=cobrancas.filter(c=>c.vencimento.startsWith(chavePeriodo)),aberto=cobrancasPeriodo.filter(c=>c.status!=="PAGA").reduce((a,c)=>a+Number(c.saldo),0),vencido=cobrancasPeriodo.filter(c=>c.status==="VENCIDA").reduce((a,c)=>a+Number(c.saldo),0);
  const aPagar=movimentos.filter(l=>l.tipo==="SAIDA"&&l.status!=="PAGO"&&l.status!=="CANCELADO").reduce((a,l)=>a+Number(l.valor),0),max=Math.max(entradas,saidas,aberto,aPagar,1);
  const barras=[['Entradas',entradas,'var(--green)'],['Saídas',saidas,'var(--red)'],['A receber',aberto,'var(--yellow)'],['A pagar',aPagar,'var(--orange)']] as const;
  const nomePeriodo=visao==="mes"?new Date(`${periodo}-02T12:00:00`).toLocaleDateString("pt-BR",{month:"long",year:"numeric"}):new Date(`${dia}T12:00:00`).toLocaleDateString("pt-BR",{day:"2-digit",month:"long",year:"numeric"});
  function moverPeriodo(delta:number){if(visao==="mes"){const d=new Date(`${periodo}-02T12:00:00`);d.setMonth(d.getMonth()+delta);setPeriodo(d.toISOString().slice(0,7))}else{const d=new Date(`${dia}T12:00:00`);d.setDate(d.getDate()+delta);setDia(d.toISOString().slice(0,10))}}
  return <main className="page" style={{maxWidth:1380}}><PageHeader title="Painel financeiro" sub="Resumo do caixa, compromissos, cobranças e resultado operacional." action={<div className="row"><button className="btn btn-ghost" onClick={()=>nav('/app/receber')}>Ver cobranças</button><button className="btn btn-primary" onClick={()=>nav('/app/lancamentos')}>Movimentar caixa</button></div>}/>{erro&&<div className="inline-error">{erro}</div>}
  <div className="grid finance-summary" style={{gridTemplateColumns:'repeat(5,1fr)',marginTop:18}}>{[['Saldo atual',resumo.saldo,'var(--green)'],['Entradas no período',entradas,'var(--green)'],['Saídas no período',saidas,'var(--red)'],['Cobranças no período',aberto,'var(--yellow)'],['A pagar no período',aPagar,'var(--orange)']].map(x=><div className="card-tight" key={String(x[0])}><div className="uplabel">{x[0]}</div><div className="num" style={{fontSize:24,color:String(x[2]),marginTop:8}}>{brl.format(Number(x[1]))}</div></div>)}</div>
  <div className="grid finance-panels" style={{gridTemplateColumns:'1.25fr .75fr',marginTop:20}}><section className="card"><div className="finance-period-head"><div><h2 className="h2">Movimentação do período</h2><p className="muted">Comparativo financeiro de {nomePeriodo}.</p></div><div className="period-picker"><div className="period-tabs"><button className={visao==="mes"?"on":""} onClick={()=>setVisao("mes")}>Por mês</button><button className={visao==="dia"?"on":""} onClick={()=>setVisao("dia")}>Por dia</button></div><div className="period-nav"><button aria-label="Período anterior" onClick={()=>moverPeriodo(-1)}>‹</button><strong>{nomePeriodo}</strong><button aria-label="Próximo período" onClick={()=>moverPeriodo(1)}>›</button></div><button className="period-today" onClick={()=>{setPeriodo(mesAtual());setDia(new Date().toISOString().slice(0,10))}}>Hoje</button></div></div><div className="finance-bars">{barras.map(b=><div className="finance-bar-row" key={b[0]}><span>{b[0]}</span><div><i style={{width:`${Number(b[1])?Math.max(5,Number(b[1])/max*100):0}%`,background:String(b[2])}}/></div><strong>{brl.format(Number(b[1]))}</strong></div>)}</div></section>
  <section className="card"><h2 className="h2">Cobranças</h2><p className="muted">Vencimentos em {nomePeriodo}.</p><div className="finance-kpi"><span>Em aberto</span><strong>{brl.format(aberto)}</strong></div><div className="finance-kpi"><span>Vencidas</span><strong style={{color:'var(--red)'}}>{brl.format(vencido)}</strong></div><div className="finance-kpi"><span>A vencer</span><strong>{brl.format(Math.max(0,aberto-vencido))}</strong></div><button className="btn btn-ghost" style={{width:'100%',marginTop:16}} onClick={()=>nav('/app/receber')}>Abrir central de cobranças</button></section></div>
  <section className="card" style={{marginTop:20}}><div className="row between"><div><h2 className="h2">Movimentos de {nomePeriodo}</h2><p className="muted">Origem, situação e conta de destino.</p></div><button className="btn btn-ghost btn-sm" onClick={()=>nav('/app/lancamentos')}>Ver fluxo completo</button></div><div className="list">{movimentos.slice(0,8).map(l=><div className="list-row" style={{gridTemplateColumns:'100px 1fr 150px 130px 130px'}} key={l.id}><strong style={{color:l.tipo==='ENTRADA'?'var(--green)':'var(--red)'}}>{l.tipo}</strong><span><strong>{l.descricao}</strong><small style={{display:'block',color:'var(--muted)'}}>{l.categoria} · {l.conta}</small></span><span>{(l.pagamento||l.vencimento).split('-').reverse().join('/')}</span><Tag cor={l.status==='PAGO'?'var(--green)':'var(--yellow)'}>{l.status}</Tag><strong className="num">{brl.format(Number(l.valor))}</strong></div>)}{!movimentos.length&&<div className="empty">Nenhuma movimentação registrada neste mês.</div>}</div></section></main>
}
