import {useEffect,useMemo,useState} from "react";
import {useSearchParams} from "react-router-dom";
import {PageHeader,Tag,useToast} from "../components/ui";
import {atendimentoApi,type ContaFinanceiraApi,type LancamentoFinanceiroApi} from "../lib/api";
import {brl} from "../lib/calc";
const hoje=()=>new Date().toISOString().slice(0,10);

export default function Lancamentos(){
  const [lista,setLista]=useState<LancamentoFinanceiroApi[]>([]),[contas,setContas]=useState<ContaFinanceiraApi[]>([]),[contaId,setContaId]=useState(""),[modal,setModal]=useState(false),[busca,setBusca]=useState("");
  const [tipo,setTipo]=useState<"ENTRADA"|"SAIDA">("ENTRADA"),[descricao,setDescricao]=useState(""),[categoria,setCategoria]=useState("Outros"),[valor,setValor]=useState(""),[vencimento,setVencimento]=useState(hoje()),[status,setStatus]=useState("ABERTO"),[forma,setForma]=useState("Pix"),[salvando,setSalvando]=useState(false); const {toast}=useToast();
  const [params]=useSearchParams();
  const carregar=()=>Promise.all([atendimentoApi.lancamentosFinanceiros(),atendimentoApi.contasFinanceiras()]).then(([l,c])=>{setLista(l);setContas(c);setContaId(atual=>atual||(c.length===1?String(c[0].id):""))});
  useEffect(()=>{void carregar()},[]); const filtrada=useMemo(()=>lista.filter(l=>(l.descricao+l.categoria+l.status).toLowerCase().includes(busca.toLowerCase())).filter(l=>params.get("filtro")!=="pagar-hoje"||(l.tipo==="SAIDA"&&l.vencimento===hoje()&&["ABERTO","VENCIDO"].includes(l.status))),[lista,busca,params]);
  async function salvar(){if(!contaId){toast("Selecione a conta financeira.");return}setSalvando(true);try{await atendimentoApi.criarLancamentoFinanceiro({tipo,descricao,categoria,valor:Number(valor.replace(",",".")),vencimento,status,forma,contaId:Number(contaId)});toast("Lançamento salvo.");setModal(false);setDescricao("");setValor("");await carregar()}catch(e){toast(e instanceof Error?e.message:"Não foi possível salvar.")}finally{setSalvando(false)}}
  async function baixar(l:LancamentoFinanceiroApi){try{await atendimentoApi.baixarLancamentoFinanceiro(l.id,{pagamento:hoje(),forma:"Pix"});toast("Pagamento confirmado.");await carregar()}catch(e){toast(e instanceof Error?e.message:"Falha ao baixar lançamento.")}}
  return <main className="page" style={{maxWidth:1350}}><PageHeader title="Lançamentos" sub="Registre entradas e saídas, acompanhe vencimentos e confirme pagamentos." action={<button className="btn btn-primary" onClick={()=>setModal(true)}>Novo lançamento</button>}/>
    <input className="input" style={{maxWidth:430,marginTop:20}} placeholder="Buscar descrição, categoria ou situação..." value={busca} onChange={e=>setBusca(e.target.value)}/>
    <div className="list-head" style={{marginTop:20,gridTemplateColumns:"100px 1.3fr 150px 130px 130px 180px"}}><span>Tipo</span><span>Descrição</span><span>Vencimento</span><span>Situação</span><span>Valor</span><span>Ações</span></div>
    <div className="list">{filtrada.map(l=><div className="list-row" style={{gridTemplateColumns:"100px 1.3fr 150px 130px 130px 180px",cursor:"default"}} key={l.id}><strong style={{color:l.tipo==="ENTRADA"?"var(--green)":"var(--red)"}}>{l.tipo}</strong><span><strong>{l.descricao}</strong><small className="muted block">{l.categoria} · {l.conta}</small></span><span>{l.vencimento.split("-").reverse().join("/")}</span><Tag cor={l.status==="PAGO"?"var(--green)":l.status==="VENCIDO"?"var(--red)":l.status==="CANCELADO"?"var(--muted)":"var(--yellow)"}>{l.status}</Tag><strong>{brl.format(Number(l.valor))}</strong><span className="row">{["ABERTO","VENCIDO"].includes(l.status)&&<><button className="btn btn-primary btn-sm" onClick={()=>baixar(l)}>Confirmar</button><button className="btn btn-ghost btn-sm" onClick={async()=>{await atendimentoApi.cancelarLancamentoFinanceiro(l.id);await carregar()}}>Cancelar</button></>}</span></div>)}</div>
    {modal&&<div className="document-modal"><div className="issue-modal"><header><div><div className="uplabel">Movimento de caixa</div><h2 className="h2">Novo lançamento</h2></div><button className="document-modal-close" onClick={()=>setModal(false)}>×</button></header>
      <div className="row" style={{marginBottom:14}}><button className={`btn ${tipo==="ENTRADA"?"btn-primary":"btn-ghost"}`} onClick={()=>setTipo("ENTRADA")}>Entrada</button><button className={`btn ${tipo==="SAIDA"?"btn-primary":"btn-ghost"}`} onClick={()=>setTipo("SAIDA")}>Saída</button></div>
      <div className="form-grid"><label className="field full"><span>Descrição</span><input className="input" value={descricao} onChange={e=>setDescricao(e.target.value)}/></label><label className="field"><span>Conta financeira</span><select className="select" value={contaId} onChange={e=>setContaId(e.target.value)}><option value="">Selecione...</option>{contas.filter(c=>c.ativo).map(c=><option value={c.id} key={c.id}>{c.nome}</option>)}</select></label><label className="field"><span>Categoria</span><select className="select" value={categoria} onChange={e=>setCategoria(e.target.value)}>{["Locações","Manutenção","Combustível","Frete","Fornecedores","Impostos","Salários","Outros"].map(c=><option key={c}>{c}</option>)}</select></label><label className="field"><span>Valor</span><input className="input" inputMode="decimal" value={valor} onChange={e=>setValor(e.target.value)}/></label><label className="field"><span>Vencimento</span><input className="input" type="date" value={vencimento} onChange={e=>setVencimento(e.target.value)}/></label><label className="field"><span>Situação</span><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option value="ABERTO">Em aberto</option><option value="PAGO">Já pago</option></select></label><label className="field"><span>Forma</span><select className="select" value={forma} onChange={e=>setForma(e.target.value)}>{["Pix","Dinheiro","Boleto","Cartão de crédito","Cartão de débito","Transferência"].map(f=><option key={f}>{f}</option>)}</select></label></div>
      <div className="row" style={{justifyContent:"flex-end",marginTop:18}}><button className="btn btn-ghost" onClick={()=>setModal(false)}>Cancelar</button><button className="btn btn-primary" disabled={salvando||descricao.trim().length<3||!valor||!contaId} onClick={salvar}>{salvando?"Salvando...":"Salvar lançamento"}</button></div>
    </div></div>}
  </main>
}
