import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { PageHeader, Tag, useToast } from "../components/ui";
import { atendimentoApi, type ManutencaoApi,type PatrimonioApi } from "../lib/api";

export default function Manutencoes() {
  const [lista,setLista]=useState<ManutencaoApi[]>([]); const [carregando,setCarregando]=useState(true); const [erro,setErro]=useState("");
  const [patrimonios,setPatrimonios]=useState<PatrimonioApi[]>([]),[form,setForm]=useState(false),[patrimonio,setPatrimonio]=useState(""),[motivo,setMotivo]=useState(""),[tipo,setTipo]=useState("CORRETIVA"),[prioridade,setPrioridade]=useState("NORMAL"),[fornecedor,setFornecedor]=useState(""),[previsao,setPrevisao]=useState(""),[custo,setCusto]=useState(0),[salvando,setSalvando]=useState(false);
  const [concluindo,setConcluindo]=useState<ManutencaoApi|null>(null),[servicoRealizado,setServicoRealizado]=useState(""),[finalizando,setFinalizando]=useState(false);
  const {toast}=useToast(); const nav=useNavigate();
  const carregar=()=>{setCarregando(true);setErro("");atendimentoApi.manutencoes().then(setLista).catch(()=>setErro("Não foi possível carregar as manutenções do servidor.")).finally(()=>setCarregando(false));};
  useEffect(()=>{carregar();void atendimentoApi.patrimonios().then(setPatrimonios)},[]);
  async function abrir(){if(!patrimonio||motivo.trim().length<10)return toast("Selecione o patrimônio e descreva o problema.");setSalvando(true);try{await atendimentoApi.abrirManutencao({patrimonio,motivo,tipo,prioridade,fornecedor,previsao,custoEstimado:custo});toast("Ordem de manutenção aberta. Patrimônio bloqueado.");setForm(false);setMotivo("");carregar()}catch(e){toast(e instanceof Error?e.message:"Falha ao abrir manutenção.")}finally{setSalvando(false)}}
  async function concluir(){if(!concluindo)return;setFinalizando(true);try{await atendimentoApi.concluirManutencao(concluindo.id,servicoRealizado.trim());toast(`${concluindo.patrimonio} liberado para novas locações.`);setConcluindo(null);setServicoRealizado("");carregar();}catch{toast("Não foi possível concluir a manutenção.");}finally{setFinalizando(false)}}
  const abertas=lista.filter(m=>m.status==="ABERTA").length;
  return <main className="page" style={{maxWidth:1300}}>
    <PageHeader title="Manutenções" sub="Ordens reais abertas manualmente ou pela inspeção. Patrimônios em manutenção ficam bloqueados para locação." action={<button className="btn btn-primary" onClick={()=>setForm(!form)}>{form?"Cancelar":"Nova manutenção"}</button>}/>
    {form&&<section className="card operation-form"><h2 className="h2">Abrir ordem de manutenção</h2><div className="grid operation-form-grid"><label className="field"><span>Patrimônio</span><select className="select" value={patrimonio} onChange={e=>setPatrimonio(e.target.value)}><option value="">Selecione...</option>{patrimonios.filter(p=>!["LOCADO","RESERVADO","MANUTENCAO"].includes(p.estado)).map(p=><option value={p.codigo} key={p.codigo}>{p.codigo} · {p.produto} · {p.estado}</option>)}</select></label><label className="field"><span>Tipo</span><select className="select" value={tipo} onChange={e=>setTipo(e.target.value)}><option value="CORRETIVA">Corretiva</option><option value="PREVENTIVA">Preventiva</option><option value="LIMPEZA">Limpeza</option><option value="REVISAO">Revisão</option></select></label><label className="field"><span>Prioridade</span><select className="select" value={prioridade} onChange={e=>setPrioridade(e.target.value)}><option value="BAIXA">Baixa</option><option value="NORMAL">Normal</option><option value="ALTA">Alta</option><option value="URGENTE">Urgente</option></select></label><label className="field"><span>Fornecedor / oficina</span><input className="input" value={fornecedor} onChange={e=>setFornecedor(e.target.value)}/></label><label className="field"><span>Previsão de conclusão</span><input className="input" type="date" value={previsao} onChange={e=>setPrevisao(e.target.value)}/></label><label className="field"><span>Custo estimado</span><div className="money-input"><span>R$</span><input type="number" min="0" value={custo||""} onChange={e=>setCusto(Number(e.target.value))}/></div></label><label className="field operation-description"><span>Problema e serviço necessário</span><textarea className="textarea" value={motivo} onChange={e=>setMotivo(e.target.value)} placeholder="Descreva sintomas, peças, testes realizados e serviço necessário..."/></label></div><button className="btn btn-primary" disabled={salvando} onClick={abrir}>{salvando?"Abrindo...":"Abrir ordem e bloquear patrimônio"}</button></section>}
    <div className="row wrap" style={{gap:12,marginTop:20}}><div className="card-tight"><span className="uplabel">Abertas</span><span className="num" style={{fontSize:24,color:abertas?"var(--red)":"var(--green)",marginLeft:12}}>{abertas}</span></div><button className="btn btn-ghost" onClick={carregar}>Atualizar</button></div>
    <div className="list-head" style={{marginTop:24,gridTemplateColumns:"100px 1.3fr 1.5fr 140px 190px"}}><span>Ordem</span><span>Equipamento</span><span>Motivo</span><span>Aberta em</span><span>Ação</span></div>
    <div className="list">{lista.map(m=><div key={m.id} className="list-row" style={{gridTemplateColumns:"100px 1.3fr 1.5fr 140px 190px",cursor:"default"}}>
      <span className="mono orange">MT-{String(m.id).padStart(5,"0")}</span><span><strong>{m.produto}</strong><small style={{display:"block",color:"var(--muted)"}}>{m.patrimonio} · <button className="link-back" onClick={()=>nav(`/app/contratos/${m.contrato}`)}>{m.contrato}</button></small></span><span className="muted" style={{fontSize:13,whiteSpace:"pre-line"}}>{m.motivo}</span><span style={{fontSize:13}}>{new Date(m.criadoEm).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})}</span><span className="row wrap" style={{gap:6}}><Tag cor={m.status==="ABERTA"?"var(--yellow)":"var(--green)"}>{m.status==="ABERTA"?"Aberta":"Concluída"}</Tag>{m.status==="ABERTA"&&<button className="btn btn-primary btn-sm" onClick={()=>setConcluindo(m)}>Concluir e liberar</button>}</span>
    </div>)}{carregando&&<div className="empty">Carregando manutenções...</div>}{!carregando&&!erro&&!lista.length&&<div className="empty">Nenhuma manutenção registrada.</div>}{erro&&<div className="empty" style={{color:"var(--red)"}}>{erro}</div>}</div>
    {concluindo&&<div className="document-modal" role="dialog" aria-modal="true" onMouseDown={e=>{if(e.target===e.currentTarget&&!finalizando)setConcluindo(null)}}><div className="issue-modal"><header><div><div className="uplabel">Conclusão da ordem MT-{String(concluindo.id).padStart(5,"0")}</div><h2 className="h2">Concluir manutenção</h2></div><button className="document-modal-close" disabled={finalizando} onClick={()=>setConcluindo(null)}>×</button></header><div className="card-tight" style={{marginBottom:16}}><strong>{concluindo.produto}</strong><small style={{display:"block",color:"var(--muted)",marginTop:4}}>{concluindo.patrimonio}</small></div><label className="field"><span>Serviço realizado</span><textarea autoFocus className="textarea" value={servicoRealizado} onChange={e=>setServicoRealizado(e.target.value)} placeholder="Informe o reparo executado, peças substituídas e testes realizados..."/></label><p className="muted" style={{fontSize:13}}>Ao concluir, o patrimônio voltará a ficar disponível para locação.</p><div className="row" style={{gap:8,justifyContent:"flex-end"}}><button className="btn btn-ghost" disabled={finalizando} onClick={()=>setConcluindo(null)}>Cancelar</button><button className="btn btn-primary" disabled={finalizando} onClick={concluir}>{finalizando?"Concluindo...":"Confirmar e liberar"}</button></div></div></div>}
  </main>;
}
