import {useEffect,useState} from "react";
import {adminApi,type UsuarioAdmin} from "../lib/api";
import {PageHeader,Tag,useToast} from "../components/ui";

export default function Usuarios(){
  const [lista,setLista]=useState<UsuarioAdmin[]>([]),[modal,setModal]=useState(false),[editando,setEditando]=useState<UsuarioAdmin|null>(null),[login,setLogin]=useState(""),[nome,setNome]=useState(""),[senha,setSenha]=useState(""),[papel,setPapel]=useState<"ADMIN"|"OPERADOR">("OPERADOR"),[salvando,setSalvando]=useState(false);const{toast}=useToast();
  const carregar=()=>adminApi.usuarios().then(setLista).catch(e=>toast(e instanceof Error?e.message:"Falha ao carregar usuários."));useEffect(()=>{void adminApi.usuarios().then(setLista).catch(()=>setLista([]))},[]);
  function novo(){setEditando(null);setLogin("");setNome("");setSenha("");setPapel("OPERADOR");setModal(true)}
  function editar(u:UsuarioAdmin){setEditando(u);setLogin(u.login);setNome(u.nome);setSenha("");setPapel(u.papel);setModal(true)}
  async function salvar(){setSalvando(true);try{if(editando){await adminApi.editarUsuario(editando.id,{nome,papel,ativo:editando.ativo});if(senha)await adminApi.alterarSenha(editando.id,senha)}else await adminApi.criarUsuario({login,nome,senha,papel});toast("Usuário salvo.");setModal(false);await carregar()}catch(e){toast(e instanceof Error?e.message:"Não foi possível salvar o usuário.")}finally{setSalvando(false)}}
  async function alternar(u:UsuarioAdmin){try{await adminApi.editarUsuario(u.id,{nome:u.nome,papel:u.papel,ativo:!u.ativo});await carregar()}catch(e){toast(e instanceof Error?e.message:"Não foi possível alterar o acesso.")}}
  return <main className="page" style={{maxWidth:1100}}><PageHeader title="Usuários" sub="Acessos internos protegidos pelo backend. Use apenas os papéis ADMIN e OPERADOR." action={<button className="btn btn-primary" onClick={novo}>Novo usuário</button>}/><div className="list-head" style={{marginTop:24,gridTemplateColumns:"1.4fr 160px 130px 170px"}}><span>Usuário</span><span>Papel</span><span>Situação</span><span>Ações</span></div><div className="list">{lista.map(u=><div className="list-row" key={u.id} style={{gridTemplateColumns:"1.4fr 160px 130px 170px",cursor:"default"}}><span><strong>{u.nome}</strong><small className="block muted">{u.login}{u.ultimo_login_em?` · último acesso ${new Date(u.ultimo_login_em).toLocaleString("pt-BR")}`:" · nunca acessou"}</small></span><Tag cor={u.papel==="ADMIN"?"var(--orange)":"var(--blue)"}>{u.papel}</Tag><Tag cor={u.ativo?"var(--green)":"var(--red)"}>{u.ativo?"Ativo":"Inativo"}</Tag><span className="row"><button className="btn btn-ghost btn-sm" onClick={()=>editar(u)}>Editar</button><button className="btn btn-ghost btn-sm" onClick={()=>alternar(u)}>{u.ativo?"Desativar":"Ativar"}</button></span></div>)}</div>{modal&&<div className="document-modal"><div className="issue-modal"><header><h2 className="h2">{editando?"Editar usuário":"Novo usuário"}</h2><button className="document-modal-close" onClick={()=>setModal(false)}>×</button></header><div className="form-grid"><label className="field"><span>Login</span><input className="input" disabled={!!editando} value={login} onChange={e=>setLogin(e.target.value)}/></label><label className="field"><span>Nome</span><input className="input" value={nome} onChange={e=>setNome(e.target.value)}/></label><label className="field"><span>Papel</span><select className="select" value={papel} onChange={e=>setPapel(e.target.value as "ADMIN"|"OPERADOR")}><option value="OPERADOR">OPERADOR</option><option value="ADMIN">ADMIN</option></select></label><label className="field"><span>{editando?"Nova senha (opcional)":"Senha"}</span><input className="input" type="password" value={senha} onChange={e=>setSenha(e.target.value)} minLength={10}/></label></div><p className="muted" style={{fontSize:13}}>Senhas devem ter ao menos 10 caracteres e nunca são exibidas novamente.</p><div className="row" style={{justifyContent:"flex-end"}}><button className="btn btn-ghost" onClick={()=>setModal(false)}>Cancelar</button><button className="btn btn-primary" disabled={salvando||nome.trim().length<3||(!editando&&senha.length<10)} onClick={salvar}>{salvando?"Salvando...":"Salvar"}</button></div></div></div>}</main>;
}
