package br.com.locago.atendimento;
import org.springframework.beans.factory.annotation.Value;import org.springframework.core.io.Resource;import org.springframework.core.io.UrlResource;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;import org.springframework.web.server.ResponseStatusException;import java.io.IOException;import java.nio.file.*;import java.util.*;
@Service public class DocumentoContratoService{
 private static final Set<String>MIMES=Set.of("application/pdf","image/jpeg","image/png");private final JdbcClient jdbc;private final Path raiz;
 public DocumentoContratoService(JdbcClient jdbc,@Value("${locago.upload-dir:/data/clientes}")String base){this.jdbc=jdbc;this.raiz=Paths.get(base).toAbsolutePath().normalize().resolve("contratos");}
 public List<Map<String,Object>>listar(String numero){return jdbc.sql("select id,tipo,nome_original,mime_type,tamanho,criado_em from documento_contrato where contrato_numero=:n order by criado_em desc").param("n",numero).query((r,i)->{Map<String,Object>m=new LinkedHashMap<>();m.put("id",r.getLong("id"));m.put("tipo",r.getString("tipo"));m.put("nome",r.getString("nome_original"));m.put("mime",r.getString("mime_type"));m.put("tamanho",r.getLong("tamanho"));m.put("criadoEm",r.getTimestamp("criado_em").toInstant().toString());return m;}).list();}
 @Transactional public Map<String,Object>salvar(String numero,String tipo,MultipartFile arq){if(jdbc.sql("select count(*) from contrato_atendimento where numero=:n").param("n",numero).query(Integer.class).single()==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Contrato não encontrado");if(arq.isEmpty()||arq.getSize()>10*1024*1024)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Arquivo vazio ou maior que 10 MB");String mime=Optional.ofNullable(arq.getContentType()).orElse("");if(!MIMES.contains(mime))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Envie um arquivo PDF, JPG ou PNG");String original=Paths.get(Optional.ofNullable(arq.getOriginalFilename()).orElse("contrato-assinado")).getFileName().toString(),ext=mime.equals("application/pdf")?".pdf":mime.equals("image/png")?".png":".jpg",nome=UUID.randomUUID()+ext;Path pasta=raiz.resolve(numero).normalize();if(!pasta.startsWith(raiz))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Caminho inválido");try{Files.createDirectories(pasta);arq.transferTo(pasta.resolve(nome));}catch(IOException e){throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,"Falha ao armazenar o contrato");}Long id=jdbc.sql("insert into documento_contrato(contrato_numero,tipo,nome_original,nome_armazenado,mime_type,tamanho) values(:c,:t,:o,:a,:m,:s) returning id").param("c",numero).param("t",tipo).param("o",original).param("a",nome).param("m",mime).param("s",arq.getSize()).query(Long.class).single();return listar(numero).stream().filter(x->x.get("id").equals(id)).findFirst().orElseThrow();}
 public Download baixar(long id){Map<String,Object>d=jdbc.sql("select contrato_numero,nome_original,nome_armazenado,mime_type from documento_contrato where id=:id").param("id",id).query((r,n)->Map.<String,Object>of("contrato",r.getString(1),"nome",r.getString(2),"arquivo",r.getString(3),"mime",r.getString(4))).optional().orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Documento não encontrado"));try{Resource r=new UrlResource(raiz.resolve(d.get("contrato").toString()).resolve(d.get("arquivo").toString()).toUri());if(!r.exists())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Arquivo não encontrado");return new Download(r,d.get("nome").toString(),d.get("mime").toString());}catch(java.net.MalformedURLException e){throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Arquivo inválido");}}
 @Transactional public void excluir(long id){Map<String,Object>d=jdbc.sql("select contrato_numero,nome_armazenado from documento_contrato where id=:id").param("id",id).query((r,n)->Map.<String,Object>of("contrato",r.getString(1),"arquivo",r.getString(2))).optional().orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Documento não encontrado"));jdbc.sql("delete from documento_contrato where id=:id").param("id",id).update();try{Files.deleteIfExists(raiz.resolve(d.get("contrato").toString()).resolve(d.get("arquivo").toString()));}catch(IOException e){throw new IllegalStateException(e);}}
 public record Download(Resource resource,String nome,String mime){}
}
