package br.com.locago.atendimento;
import org.springframework.beans.factory.annotation.Value;import org.springframework.core.io.Resource;import org.springframework.core.io.UrlResource;import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;import org.springframework.web.server.ResponseStatusException;
import java.io.IOException;import java.nio.file.*;import java.util.*;
@Service public class DocumentoClienteService{
 private final JdbcClient jdbc;private final Path raiz;private static final Set<String>MIMES=Set.of("application/pdf","image/jpeg","image/png");
 public DocumentoClienteService(JdbcClient jdbc,@Value("${locago.upload-dir:/data/clientes}")String dir){this.jdbc=jdbc;this.raiz=Paths.get(dir).toAbsolutePath().normalize();try{Files.createDirectories(raiz);}catch(IOException e){throw new IllegalStateException(e);}}
 public List<Map<String,Object>> listar(String cliente){return jdbc.sql("select id,tipo,nome_original,mime_type,tamanho,criado_em from documento_cliente where cliente_id=:c order by criado_em desc").param("c",cliente).query((r,n)->{Map<String,Object>m=new LinkedHashMap<>();m.put("id",r.getLong("id"));m.put("tipo",r.getString("tipo"));m.put("nome",r.getString("nome_original"));m.put("mime",r.getString("mime_type"));m.put("tamanho",r.getLong("tamanho"));m.put("criadoEm",r.getTimestamp("criado_em").toInstant().toString());return m;}).list();}
 @Transactional public Map<String,Object> salvar(String cliente,String tipo,MultipartFile arquivo){if(jdbc.sql("select count(*) from cliente_atendimento where id=:id").param("id",cliente).query(Integer.class).single()==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Cliente não encontrado");if(arquivo.isEmpty()||arquivo.getSize()>10*1024*1024)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Arquivo vazio ou maior que 10 MB");String mime=Optional.ofNullable(arquivo.getContentType()).orElse("");if(!MIMES.contains(mime))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Formato não permitido");String original=Paths.get(Optional.ofNullable(arquivo.getOriginalFilename()).orElse("documento")).getFileName().toString();String ext=mime.equals("application/pdf")?".pdf":mime.equals("image/png")?".png":".jpg";String armazenado=UUID.randomUUID()+ext;Path pasta=raiz.resolve(cliente).normalize();if(!pasta.startsWith(raiz))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Caminho inválido");try{Files.createDirectories(pasta);arquivo.transferTo(pasta.resolve(armazenado));}catch(IOException e){throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR,"Falha ao armazenar arquivo");}Long id=jdbc.sql("insert into documento_cliente(cliente_id,tipo,nome_original,nome_armazenado,mime_type,tamanho) values(:c,:t,:n,:a,:m,:s) returning id").param("c",cliente).param("t",tipo.isBlank()?"Outro":tipo).param("n",original).param("a",armazenado).param("m",mime).param("s",arquivo.getSize()).query(Long.class).single();return listar(cliente).stream().filter(d->d.get("id").equals(id)).findFirst().orElseThrow();}
 public Download baixar(long id){Map<String,Object>d=jdbc.sql("select cliente_id,nome_original,nome_armazenado,mime_type from documento_cliente where id=:id").param("id",id).query((r,n)->Map.<String,Object>of("cliente",r.getString("cliente_id"),"nome",r.getString("nome_original"),"armazenado",r.getString("nome_armazenado"),"mime",r.getString("mime_type"))).optional().orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Documento não encontrado"));try{Resource r=new UrlResource(raiz.resolve(d.get("cliente").toString()).resolve(d.get("armazenado").toString()).toUri());if(!r.exists())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Arquivo não encontrado");return new Download(r,d.get("nome").toString(),d.get("mime").toString());}catch(java.net.MalformedURLException e){throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Arquivo inválido");}}
 @Transactional public void excluir(long id){Map<String,Object>d=jdbc.sql("select cliente_id,nome_armazenado from documento_cliente where id=:id").param("id",id).query((r,n)->Map.<String,Object>of("cliente",r.getString("cliente_id"),"arquivo",r.getString("nome_armazenado"))).optional().orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Documento não encontrado"));jdbc.sql("delete from documento_cliente where id=:id").param("id",id).update();try{Files.deleteIfExists(raiz.resolve(d.get("cliente").toString()).resolve(d.get("arquivo").toString()));}catch(IOException e){throw new IllegalStateException("Falha ao excluir arquivo",e);}}
 public record Download(Resource resource,String nome,String mime){}
}
