package br.com.locago.atendimento;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import java.util.*;
@Service public class EventoOperacionalService{
 private final JdbcClient jdbc; public EventoOperacionalService(JdbcClient jdbc){this.jdbc=jdbc;}
 public List<Map<String,Object>> listar(String tipo){return jdbc.sql("select e.id,e.tipo,e.contrato_numero contrato,e.categoria,e.descricao,e.prioridade,e.patrimonio_origem,e.patrimonio_destino,e.status,e.responsavel,e.criado_em,e.concluido_em,coalesce(c.dados->>'clienteId','') cliente_id from operacao_evento e join contrato_atendimento c on c.numero=e.contrato_numero where e.tipo=:tipo order by e.criado_em desc").param("tipo",tipo).query((r,n)->map(r)).list();}
 public Map<String,Object> criar(String tipo,Map<String,Object>b){String contrato=s(b,"contrato"),categoria=s(b,"categoria"),descricao=s(b,"descricao");if(contrato.isBlank()||categoria.isBlank()||descricao.length()<10)throw new IllegalArgumentException("Informe contrato, categoria e uma descrição detalhada");Long id=jdbc.sql("insert into operacao_evento(tipo,contrato_numero,categoria,descricao,prioridade,patrimonio_origem,patrimonio_destino,responsavel) values(:t,:c,:cat,:d,:p,:o,:n,:r) returning id").param("t",tipo).param("c",contrato).param("cat",categoria).param("d",descricao).param("p",s(b,"prioridade").isBlank()?"NORMAL":s(b,"prioridade")).param("o",s(b,"patrimonioOrigem")).param("n",s(b,"patrimonioDestino")).param("r",s(b,"responsavel").isBlank()?"Rafael M.":s(b,"responsavel")).query(Long.class).single();return buscar(id);}
 public Map<String,Object> concluir(long id){jdbc.sql("update operacao_evento set status='CONCLUIDA',concluido_em=now() where id=:id").param("id",id).update();return buscar(id);}
 private Map<String,Object> buscar(long id){return jdbc.sql("select e.id,e.tipo,e.contrato_numero contrato,e.categoria,e.descricao,e.prioridade,e.patrimonio_origem,e.patrimonio_destino,e.status,e.responsavel,e.criado_em,e.concluido_em,coalesce(c.dados->>'clienteId','') cliente_id from operacao_evento e join contrato_atendimento c on c.numero=e.contrato_numero where e.id=:id").param("id",id).query((r,n)->map(r)).single();}
 private Map<String,Object> map(java.sql.ResultSet r)throws java.sql.SQLException{Map<String,Object>m=new LinkedHashMap<>();m.put("id",r.getLong("id"));m.put("tipo",r.getString("tipo"));m.put("contrato",r.getString("contrato"));m.put("categoria",r.getString("categoria"));m.put("descricao",r.getString("descricao"));m.put("prioridade",r.getString("prioridade"));m.put("patrimonioOrigem",r.getString("patrimonio_origem"));m.put("patrimonioDestino",r.getString("patrimonio_destino"));m.put("status",r.getString("status"));m.put("responsavel",r.getString("responsavel"));m.put("criadoEm",r.getTimestamp("criado_em").toInstant().toString());m.put("concluidoEm",r.getTimestamp("concluido_em")==null?null:r.getTimestamp("concluido_em").toInstant().toString());m.put("clienteId",r.getString("cliente_id"));return m;}
 private String s(Map<String,Object>b,String k){return String.valueOf(b.getOrDefault(k,"")).trim();}
}
