package br.com.locago.atendimento;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import java.util.*;
import org.springframework.transaction.annotation.Transactional;
@Service public class ProdutoCatalogoService{
 private final JdbcClient jdbc;private final ObjectMapper json;public ProdutoCatalogoService(JdbcClient jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}
 public List<Map<String,Object>> listar(){return jdbc.sql("select dados::text from produto_catalogo where ativo order by dados->>'nome'").query(String.class).list().stream().map(this::ler).toList();}
 public List<Map<String,Object>> categorias(){return jdbc.sql("select id,nome,prefixo from categoria_produto where ativo order by nome").query((r,n)->Map.<String,Object>of("id",r.getLong("id"),"nome",r.getString("nome"),"prefixo",r.getString("prefixo"))).list();}
 public List<Map<String,Object>> patrimonios(String produto){return jdbc.sql("select codigo,coalesce(serie,'') serie,estado from patrimonio_atendimento where produto_id=:p order by codigo").param("p",produto).query((r,n)->Map.<String,Object>of("cod",r.getString("codigo"),"serie",r.getString("serie"),"estado",r.getString("estado"),"prod",produto,"local","Galpão","horimetro","0 h","proxima","Sem programação")).list();}
 public List<Map<String,Object>> patrimonios(){return jdbc.sql("select pa.codigo,pa.produto_id,pa.serie,pa.estado,p.nome from patrimonio_atendimento pa join produto_atendimento p on p.id=pa.produto_id order by p.nome,pa.codigo").query((r,n)->Map.<String,Object>of("codigo",r.getString("codigo"),"produtoId",r.getString("produto_id"),"produto",r.getString("nome"),"serie",r.getString("serie"),"estado",r.getString("estado"))).list();}
 public Map<String,Object> categoria(Map<String,Object>b){String nome=s(b,"nome"),prefixo=s(b,"prefixo").toUpperCase().replaceAll("[^A-Z]","");if(nome.length()<3||prefixo.length()<2)throw new IllegalArgumentException("Informe nome e prefixo da categoria");Long id=jdbc.sql("insert into categoria_produto(nome,prefixo) values(:n,:p) returning id").param("n",nome).param("p",prefixo).query(Long.class).single();return Map.of("id",id,"nome",nome,"prefixo",prefixo);}
 public Map<String,Object> buscar(String id){return jdbc.sql("select dados::text from produto_catalogo where id=:id and ativo").param("id",id).query(String.class).optional().map(this::ler).orElseThrow(()->new NoSuchElementException("Produto não encontrado"));}
 @Transactional public Map<String,Object> salvar(Map<String,Object>p){String id=s(p,"id").toUpperCase().replaceAll("[^A-Z0-9_-]","");if(id.length()<2)throw new IllegalArgumentException("Código do produto inválido");if(s(p,"nome").length()<3||s(p,"categoria").length()<3||s(p,"marca").length()<2||s(p,"modelo").length()<1)throw new IllegalArgumentException("Informe nome, categoria, marca e modelo");for(String k:List.of("diaria","semanal","quinzenal","mensal","reposicao"))if(numero(p,k)<0)throw new IllegalArgumentException("Valores não podem ser negativos");p.put("id",id);p.put("controle","patrimonio");try{String dados=json.writeValueAsString(p);jdbc.sql("insert into produto_catalogo(id,dados) values(:id,cast(:d as jsonb)) on conflict(id) do update set dados=excluded.dados,ativo=true,atualizado_em=now()").param("id",id).param("d",dados).update();int qtd=Math.max(1,(int)numero(p,"unidades"));jdbc.sql("insert into produto_atendimento(id,nome,capacidade) values(:id,:n,:q) on conflict(id) do update set nome=excluded.nome,capacidade=greatest(produto_atendimento.capacidade,excluded.capacidade)").param("id",id).param("n",s(p,"nome")).param("q",qtd).update();String pref=s(p,"prefixo").toUpperCase();for(int i=1;i<=qtd;i++){String codigo=pref+"-"+String.format("%04d",i);jdbc.sql("insert into patrimonio_atendimento(codigo,produto_id,serie) values(:c,:p,:s) on conflict do nothing").param("c",codigo).param("p",id).param("s","A informar").update();}return p;}catch(Exception e){if(e instanceof IllegalArgumentException)throw (IllegalArgumentException)e;throw new IllegalArgumentException("Já existe um produto com esse nome ou código");}}
 private double numero(Map<String,Object>p,String k){try{return Double.parseDouble(String.valueOf(p.getOrDefault(k,0)));}catch(Exception e){throw new IllegalArgumentException("Valor inválido: "+k);}}
 @SuppressWarnings("unchecked")private Map<String,Object>ler(String s){try{return json.readValue(s,Map.class);}catch(Exception e){throw new IllegalStateException(e);}}private String s(Map<String,Object>p,String k){return String.valueOf(p.getOrDefault(k,"")).trim();}
}
